@startuml

[*] -> [*] : new RingBuffer(capacity < 1)
[*] --> empty : new RingBuffer(capacity >= 1)

empty --> [*] : peek[size = 0]
empty --> [*] : dequeue[size = 0]
empty --> filled : enqueue

filled --> filled : peek[size > 0]
filled --> empty : dequeue[size = 0]
filled --> filled : enqueue[size + 1 < capacity]
filled --> full : enqueue[size = capacity]

full --> filled : dequeue
full --> full : peek[size > 0]
full --> full : enqueue[size = capacity]

@enduml
